server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: shopping-user
          uri: lb://shopping-user
          predicates:
            - Path=/user/**
            - After=2023-07-20T17:42:47.789+08:00[Asia/Shanghai]
          filters:
            - AddRequestHeader=X-Request-color, blue
        - id: shopping-order
          uri: lb://shopping-order
          predicates:
            - Path=/order/**
      default-filters:
        - AddRequestHeader=X-Request-msg, Hello world!
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8100"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期,单位 秒


